const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let sessionId=null, turnHistory=[], products=[], lastDebug=null;
const stages=[['input','INPUT'],['parse','PARSE'],['state','DIALOG STATE'],['query','QUERY'],['retrieval','BM25'],['exact','EXACT'],['fusion','FUSION'],['freshness','FRESHNESS'],['output','TOP 10']];
const pipeline=$('#pipeline');
pipeline.innerHTML=stages.map((s,i)=>`<button class="stage" data-key="${s[0]}"><span>0${i+1}</span><b>${s[1]}</b></button>`).join('');
const toast=t=>{const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)};
async function reset(){let data={};const r=await fetch('/api/reset',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});try{data=await r.json()}catch{}if(!r.ok)throw Error(data.error||'reset failed');sessionId=data.session_id;turnHistory=[];products=[];lastDebug=null;$('#session').textContent=`SESSION ${String(sessionId||'—').toUpperCase()}`;$('#input').placeholder='Describe what you’re shopping for…';$('#messages').innerHTML=`<div class="welcome"><span>✦</span><h3>What are you looking for?</h3><p>I’ll remember what matters as we narrow it down.</p><div class="chips"><button>I'm looking for running shoes.</button><button>Find me a leather belt.</button><button>I need a winter jacket.</button></div></div>`;bindChips();$('#products').className='products empty';$('#products').innerHTML='<p>Your shortlist will appear here.</p>';$('#result-count').textContent='WAITING FOR INPUT';$('#turn-history').innerHTML='<i>No turns yet</i>';$('#state-view').innerHTML='';$$('.stage').forEach(x=>x.className='stage');$('#trace-detail').innerHTML='<p>Send a message to trace it through the production pipeline.</p>';toast('Fresh session started')}
function bindChips(){$$('.chips button').forEach(b=>b.onclick=()=>send(b.textContent))}
function bubble(role,text,meta=''){const w=$('#messages');$('.welcome')?.remove();const label=role==='bot'?'<span class="assistant-label">QUESTION FOR YOU</span>':'';w.insertAdjacentHTML('beforeend',`<div class="bubble ${role}">${label}<span class="bubble-text">${esc(text)}</span>${meta?`<small>${esc(meta)}</small>`:''}</div>`);w.scrollTop=w.scrollHeight}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function send(message){if(!message.trim())return;bubble('user',message,`TURN ${turnHistory.length+1} · YOU`);$('#input').value='';$('#input').disabled=true;animate();try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sessionId,message})});const data=await r.json();if(!r.ok)throw Error(data.error);lastDebug=data.debug;products=data.recommendations;turnHistory.push({message,debug:data.debug});const assistantText=data.next_question||data.message;bubble('bot',assistantText,`ASKED ATTRIBUTE: ${data.ask_attribute?.toUpperCase()||'NONE'} · ANSWER BELOW TO CONTINUE`);$('#input').placeholder='Answer the assistant’s question…';renderProducts();renderState();renderTurns();setTimeout(()=>activate(8),700)}catch(e){bubble('bot',`I couldn't complete that request: ${e.message}`)}finally{$('#input').disabled=false;$('#input').focus()}}
function animate(){let i=0;$$('.stage').forEach(x=>x.className='stage');const timer=setInterval(()=>{if(i)$$('.stage')[i-1].classList.replace('active','complete');if(i>=9)return clearInterval(timer);$$('.stage')[i++].classList.add('active')},75)}
function activate(i){$$('.stage').forEach((x,n)=>x.className='stage '+(n<i?'complete':n===i?'active':''))}
function renderProducts(){$('#products').className='products';$('#result-count').textContent=`${products.length} PRODUCTS · TURN ${lastDebug.turn}`;$('#products').innerHTML=products.map(p=>`<article class="product" data-asin="${esc(p.parent_asin)}"><span class="rank">#${String(p.final_rank).padStart(2,'0')}</span><div class="badges">${p.exact_evidence?'<span class="badge exact">EXACT</span>':''}${p.promoted?'<span class="badge">↑ PROMOTED</span>':''}</div><h4>${esc(p.title||'Catalog product')}</h4><div class="product-meta">${p.price!=null?`<b>$${esc(p.price)}</b>`:''}${p.rating!=null?`<span>★ ${esc(p.rating)}${p.rating_count?` · ${Number(p.rating_count).toLocaleString()} ratings`:''}</span>`:''}</div><footer><span>${esc(p.parent_asin)}</span></footer></article>`).join('');$$('.product').forEach(x=>x.onclick=()=>inspect(products.find(p=>p.parent_asin===x.dataset.asin)))}
function renderState(){const d=lastDebug,a=d.state_after,b=d.state_before;const list=x=>x.length?`<ul>${x.map(v=>`<li><b>${esc(v.attribute)}</b><span>${esc(v.text)}</span></li>`).join('')}</ul>`:'<p class="none">None</p>';$('#state-view').innerHTML=`<div class="state-summary"><span><small>TURN</small><b>${d.turn}</b></span><span><small>OVERRIDE</small><b>${d.override_detected?'YES':'NO'}</b></span><span><small>SHOWN</small><b>${a.shown_count}</b></span><span><small>LAST ASKED</small><b>${esc(d.ask_attribute||'—')}</b></span></div><div class="state-card"><h4>ACTIVE CONSTRAINTS</h4>${list(a.active)}</div><div class="state-card soft-state"><h4>SOFT / PREVIOUS CONSTRAINTS</h4>${list(a.soft)}</div>${d.override_detected?`<div class="state-card state-change"><h4>OVERRIDE CHANGE</h4><p><span>Before</span> ${esc(b.active.map(x=>x.text).join(' + ')||'none')}</p><p><span>After</span> ${esc(a.active.map(x=>x.text).join(' + ')||'none')}</p></div>`:''}<div class="state-card"><h4>SESSION CONTEXT</h4><p class="state-line"><span>Scenario</span><b>${esc(a.scenario)}</b></p><p class="state-line"><span>Category</span><b>${esc(a.category||'—')}</b></p></div>`}
function renderTurns(){$('#turn-history').innerHTML=turnHistory.map((t,i)=>`<span class="turn-pill">TURN ${i+1} · ${t.debug.override_detected?'↻ OVERRIDE · ':''}${esc(t.debug.state_after.active.map(x=>x.text).join(' + ')||t.message.slice(0,34))}</span>`).join('')}
function inspect(p){$('#inspector-content').innerHTML=`<span class="eyebrow">WHY THIS RESULT?</span><h2>${esc(p.title||p.parent_asin)}</h2><dl><dt>Final output rank</dt><dd>#${p.final_rank}</dd><dt>BM25 rank</dt><dd>${p.bm25_rank?'#'+p.bm25_rank:'fallback fill'}</dd><dt>Post-fusion rank</dt><dd>${p.fused_rank?'#'+p.fused_rank:'—'}</dd><dt>Exact evidence</dt><dd>${p.exact_evidence?'YES (+0.35)':'NO'}</dd><dt>Bucket evidence</dt><dd>${p.bucket_evidence?'YES (+0.10)':'NO'}</dd><dt>Promoted</dt><dd>${p.promoted?'YES':'NO'}</dd><dt>Previously shown</dt><dd>${p.previously_shown?'YES':'NO'}</dd><dt>ASIN</dt><dd>${esc(p.parent_asin)}</dd><dt>Price</dt><dd>${p.price!=null?'$'+p.price:'not supplied'}</dd><dt>Rating</dt><dd>${p.rating??'not supplied'}</dd></dl>${p.features?.length?`<h3>Catalog evidence</h3><ul>${p.features.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}`;$('#inspector').classList.add('open')}
const detail={input:d=>[`TURN ${d.turn} · RAW CUSTOMER MESSAGE`,d.raw_message],parse:d=>['PARSING / NORMALIZATION',`Parser: ${d.parser}\nLLM fallback: ${d.llm_fallback}\nOverride detected: ${d.override_detected}`],state:d=>['REMEMBERED DIALOG STATE',`Active constraints:\n${d.state_after.active.map(x=>`• ${x.attribute}: ${x.text}`).join('\n')||'None'}\n\nSoft / previous:\n${d.state_after.soft.map(x=>`• ${x.text}`).join('\n')||'None'}\n\nShown products: ${d.state_after.shown_count}`],query:d=>['CUMULATIVE RETRIEVAL QUERY',d.retrieval_query],retrieval:d=>['BM25 / ROUTES',`Catalog size: ${d.catalog_size.toLocaleString()}\nBM25 candidates: ${d.route_counts.bm25||0} / ${d.candidate_limit}\nBucket evidence: ${d.route_counts.bucket||0}\nTop BM25 samples: ${JSON.stringify(d.route_samples.bm25||[],null,2)}`],exact:d=>['EXACT / STRUCTURED EVIDENCE',`Exact candidates: ${d.route_counts.exact||0}\nOverlap with BM25: ${d.bm25_exact_overlap}\nSupported: ${d.exact_supported.join('; ')||'none'}\nUnsupported (no veto): ${d.exact_unsupported.join('; ')||'none'}`],fusion:d=>['RANKING / FUSION',`BM25 candidates remain the admission pool.\nExact membership: +${d.fusion.exact_boost}\nBucket membership: +${d.fusion.bucket_boost}\nDense: ${d.fusion.dense_enabled?'enabled':'disabled'} (weight ${d.fusion.dense_weight})`],freshness:d=>['FRESHNESS',`Previously shown: ${d.shown_before}\nEligible fused items seen before: ${d.freshness_filtered}\nShown after turn: ${d.shown_after}\nOverride reset: ${d.override_reset}`],output:d=>['TOP 10 + NEXT QUESTION',`${products.length} recommendations returned\nAsked attribute: ${d.ask_attribute||'none'}\nNext question: ${d.next_question||'none'}\n\nFinal IDs:\n${products.map(p=>`${p.final_rank}. ${p.parent_asin}`).join('\n')}`]};
$$('.stage').forEach(x=>x.onclick=()=>{if(!lastDebug)return toast('Send a message first');const [h,v]=detail[x.dataset.key](lastDebug);$('#trace-detail').innerHTML=`<h4>${h}</h4><pre>${esc(v)}</pre>`;$$('.stage').forEach(y=>y.classList.remove('active'));x.classList.add('active')});
$('#chat-form').onsubmit=e=>{e.preventDefault();send($('#input').value)};$('#reset').onclick=reset;$('#close-inspector').onclick=()=>$('#inspector').classList.remove('open');$$('.viewtabs button').forEach(b=>b.onclick=()=>{$$('.viewtabs button').forEach(x=>x.classList.toggle('active',x===b));$('#products').classList.toggle('hidden',b.dataset.view!=='products');$('#state-view').classList.toggle('hidden',b.dataset.view!=='state')});$$('.member-tabs button').forEach(b=>b.onclick=()=>{$$('.member-tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.member-panel').forEach(x=>x.classList.toggle('active',x.id===b.dataset.member))});reset();
